### ISSUE TITLE
Dependency on both lodash and lodash-es

### ISSUE THREAD

**Issue by sliptype** [react-restart/hooks#32]
I was checking out the production bundle for an app that uses `lodash-es`and noticed that `lodash` is also included.

Looking in `package.json` for `@restart/hooks` shows dependencies on both. And it looks like babel is doing an import rename to `lodash-es`.

Is the dependency on `lodash` still required?

**Comment by jquense** [comment]
yes it's required for the CommonJs builds, different lodashs are used depending on if using the es modules based build or the common js one

**Comment by sliptype** [comment]
Ah ok,

It didn't get tree-shaken because there was a reference to it in my own project. Thanks!
