### ISSUE TITLE
Remove lodash dependency

### ISSUE THREAD

**Issue by kwasimensah** [react-restart/hooks#34]
Per https://npmjs.com/advisories/1523. It seems like it's only used for isEqual  in useMutationObserver

**Comment by TrySound** [comment]
Dequal can be used as alternative.
https://github.com/lukeed/dequal

**Comment by jquense** [comment]
why tho? whats the size difference and where is the good money on dequal practically adding weight b/c now a user has both lodash (from other deps or their own app) and dequal in their bundle

**Comment by TrySound** [comment]
Lodash usage adds complexity for es modules consumers. Some users do not alias lodash to lodash-es and has bloated bundle. Lodash does not do a good job with esm. dequal has everything necessary out of the box without additional configuration.

**Comment by kwasimensah** [comment]
What @TrySound said. I'm personally more concerned about the advisory and Lodash's response to it (https://github.com/lodash/lodash/issues/4744#issuecomment-653162029). This is my project's only dependency path to lodash in production.

**Comment by TrySound** [comment]
Also look dequal is much smaller than lodash isEqual
https://bundlephobia.com/result?p=lodash.isequal@4.5.0
https://bundlephobia.com/result?p=dequal@1.0.0

**Comment by scott-r-lindsey** [comment]
I'd like to second the motion that if possible, this project should **move away from Lodash**.  

Lodash seems to be in trouble -- their release process is broken and on one on the project seems to know how to fix it.
https://github.com/lodash/lodash/issues/4879
